module.exports = {
  Introduccion: [
    {
      type: 'autogenerated',
      dirName: 'introduccion',
    },
    {
      type: 'link',
      label: 'Normas académicas y administrativas',
      href: 'http://sistemas-utnfra.com.ar/Reglamento.pdf'
    },
  ],
  Clases: [    
    "clases/programa",
    "clases/referencias",
     {
      type: 'category',
      label: 'Introducción a .NET y C#',
      collapsible: true,
      collapsed: true,
      items:
      [
        {
          type: 'autogenerated',
          dirName: 'clases/01-introduccion',
        }
      ]
    },
    {
      type: 'category',
      label: 'Métodos estáticos',      
      collapsible: true,
      collapsed: true,
      items:
      [
        {
          type: 'autogenerated',
          dirName: 'clases/02-estaticos',
        }
      ]
    },
/*    {
      type: 'category',
      label: 'Programación orientada a objetos',
      collapsible: true,
      collapsed: true,
      items:
      [
        {
          type: 'autogenerated',
          dirName: 'clases/03-objetos',
        }
      ]
    },
    {
      type: 'category',
      label: 'Sobrecarga',      
      collapsible: true,
      collapsed: true,
      items:
      [
        {
          type: 'autogenerated',
          dirName: 'clases/04-sobrecarga',
        }
      ]
    },
    {
      type: 'category',
      label: 'Windows Forms',      
      collapsible: true,
      collapsed: true,
      items:
      [
        {
          type: 'autogenerated',
          dirName: 'clases/05-forms',
        }
      ]
    },
    {
      type: 'category',
      label: 'Colecciones',      
      collapsible: true,
      collapsed: true,
      items:
      [
        {
          type: 'autogenerated',
          dirName: 'clases/06-colecciones',
        }
      ]
    },
    {
      type: 'category',
      label: 'Encapsulamiento, propiedades e indexadores',      
      collapsible: true,
      collapsed: true,
      items:
      [
        {
          type: 'autogenerated',
          dirName: 'clases/07-encapsulamiento',
        }
      ]
    },
    {
      type: 'category',
      label: 'Herencia',      
      collapsible: true,
      collapsed: true,
      items:
      [
        {
          type: 'autogenerated',
          dirName: 'clases/08-herencia',
        }
      ]
    },
    {
      type: 'category',
      label: 'Polimorfismo',      
      collapsible: true,
      collapsed: true,
      items:
      [
        {
          type: 'autogenerated',
          dirName: 'clases/09-polimorfismo',
        }
      ]
    },
    {
      type: 'category',
      label: 'Clases y métodos abstractos',      
      collapsible: true,
      collapsed: true,
      items:
      [
        {
          type: 'autogenerated',
          dirName: 'clases/10-abstract',
        }
      ]
    },
    {
      type: 'category',
      label: 'Excepciones',      
      collapsible: true,
      collapsed: true,
      items:
      [
        {
          type: 'autogenerated',
          dirName: 'clases/11-excepciones',
        }
      ]
    },
    {
      type: 'category',
      label: 'Pruebas unitarias',      
      collapsible: true,
      collapsed: true,
      items:
      [
        {
          type: 'autogenerated',
          dirName: 'clases/12-testing',
        }
      ]
    },
    {
      type: 'category',
      label: 'Tipos genéricos',
      collapsible: true,
      collapsed: true,
      items:
      [
        {
          type: 'autogenerated',
          dirName: 'clases/13-generics',
        }
      ]
    },
    {
      type: 'category',
      label: 'Interfaces',
      collapsible: true,
      collapsed: true,
      items:
      [
        {
          type: 'autogenerated',
          dirName: 'clases/14-interfaces',
        }
      ]
    },
    {
      type: 'category',
      label: 'Archivos y serialización',
      collapsible: true,
      collapsed: true,
      items:
      [
        {
          type: 'autogenerated',
          dirName: 'clases/15-serializacion',
        }
      ]
    },
    {
      type: 'category',
      label: 'Introducción a SQL',
      collapsible: true,
      collapsed: true,
      items:
      [
        {
          type: 'autogenerated',
          dirName: 'clases/16-sql',
        }
      ]
    },
    {
      type: 'category',
      label: 'Conexión a bases de datos',
      collapsible: true,
      collapsed: true,
      items:
      [
        {
          type: 'autogenerated',
          dirName: 'clases/17-databases',
        }
      ]
    },
    {
      type: 'category',
      label: 'Delegados y expresiones lambda',
      collapsible: true,
      collapsed: true,
      items:
      [
        {
          type: 'autogenerated',
          dirName: 'clases/18-delegados',
        }
      ]
    },
    {
      type: 'category',
      label: 'Programación multi-hilo y concurrencia',
      collapsible: true,
      collapsed: true,
      items:
      [
        {
          type: 'autogenerated',
          dirName: 'clases/19-concurrencia',
        }
      ],
    },
    {
      type: 'category',
      label: 'Eventos',
      collapsible: true,
      collapsed: true,
      items:
      [
        {
          type: 'autogenerated',
          dirName: 'clases/20-eventos',
        }
      ]
    },
    {
      type: 'category',
      label: 'Métodos de extensión',
      collapsible: true,
      collapsed: true,
      items:
      [
        {
          type: 'autogenerated',
          dirName: 'clases/21-otros',
        }
      ]
    }*/
  ],
/*   Evaluaciones: [
    {
      type: 'autogenerated',
      dirName: 'evaluaciones',
    }
  ],  */
};
